package bushigen.nongo.model;

import java.util.Date;

public class EmailVerificationTokens {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_verification_tokens.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_verification_tokens.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_verification_tokens.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_verification_tokens.expires_at
     *
     * @mbg.generated
     */
    private Date expiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_verification_tokens.is_active
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_verification_tokens.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_verification_tokens.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_verification_tokens.id
     *
     * @return the value of email_verification_tokens.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_verification_tokens.id
     *
     * @param id the value for email_verification_tokens.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_verification_tokens.user_id
     *
     * @return the value of email_verification_tokens.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_verification_tokens.user_id
     *
     * @param userId the value for email_verification_tokens.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_verification_tokens.token
     *
     * @return the value of email_verification_tokens.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_verification_tokens.token
     *
     * @param token the value for email_verification_tokens.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_verification_tokens.expires_at
     *
     * @return the value of email_verification_tokens.expires_at
     *
     * @mbg.generated
     */
    public Date getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_verification_tokens.expires_at
     *
     * @param expiresAt the value for email_verification_tokens.expires_at
     *
     * @mbg.generated
     */
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_verification_tokens.is_active
     *
     * @return the value of email_verification_tokens.is_active
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_verification_tokens.is_active
     *
     * @param isActive the value for email_verification_tokens.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_verification_tokens.created_at
     *
     * @return the value of email_verification_tokens.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_verification_tokens.created_at
     *
     * @param createdAt the value for email_verification_tokens.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_verification_tokens.updated_at
     *
     * @return the value of email_verification_tokens.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_verification_tokens.updated_at
     *
     * @param updatedAt the value for email_verification_tokens.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}