package bushigen.nongo.model;

import java.util.Date;

public class SoftwareEngineer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column software_engineer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column software_engineer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column software_engineer.tech_stack
     *
     * @mbg.generated
     */
    private String techStack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column software_engineer.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column software_engineer.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column software_engineer.id
     *
     * @return the value of software_engineer.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column software_engineer.id
     *
     * @param id the value for software_engineer.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column software_engineer.name
     *
     * @return the value of software_engineer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column software_engineer.name
     *
     * @param name the value for software_engineer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column software_engineer.tech_stack
     *
     * @return the value of software_engineer.tech_stack
     *
     * @mbg.generated
     */
    public String getTechStack() {
        return techStack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column software_engineer.tech_stack
     *
     * @param techStack the value for software_engineer.tech_stack
     *
     * @mbg.generated
     */
    public void setTechStack(String techStack) {
        this.techStack = techStack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column software_engineer.created_at
     *
     * @return the value of software_engineer.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column software_engineer.created_at
     *
     * @param createdAt the value for software_engineer.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column software_engineer.updated_at
     *
     * @return the value of software_engineer.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column software_engineer.updated_at
     *
     * @param updatedAt the value for software_engineer.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}