package bushigen.nongo.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * DTO for SoftwareEngineer API responses.
 * This class represents the data structure returned to API clients.
 *
 * Includes the ID field which is generated by the database.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Response data for software engineer")
public class SoftwareEngineerResponse {

    @Schema(description = "Unique identifier of the software engineer", example = "1")
    private Integer id;

    @Schema(description = "Name of the software engineer", example = "田中太郎")
    private String name;

    @Schema(description = "Technology stack and skills", example = "Java, Spring Boot, MySQL")
    private String techStack;
}
