package bushigen.nongo.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * DTO for creating new SoftwareEngineer records.
 * Note: No ID field as it's auto-generated by the database.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Request data for creating a new software engineer")
public class SoftwareEngineerCreateRequest {

    @Schema(description = "Name of the software engineer", example = "田中太郎", required = true)
    private String name;

    @Schema(description = "Technology stack and skills", example = "Java, Spring Boot, MySQL")
    private String techStack;
}
