/* tslint:disable */
/* eslint-disable */
/**
 * nongo for Bushigen
 * Management system for Bushigen family
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
    /**
     * User name (alphanumeric, more than 5 characters)
     * @type {string}
     * @memberof SignupRequest
     */
    userName: string;
    /**
     * Email address
     * @type {string}
     * @memberof SignupRequest
     */
    email: string;
    /**
     * Password (at least 8 characters, must include number and special character !@?_#&)
     * @type {string}
     * @memberof SignupRequest
     */
    password: string;
}

/**
 * Check if a given object implements the SignupRequest interface.
 */
export function instanceOfSignupRequest(value: object): value is SignupRequest {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignupRequestFromJSON(json: any): SignupRequest {
    return SignupRequestFromJSONTyped(json, false);
}

export function SignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['user_name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignupRequestToJSON(json: any): SignupRequest {
    return SignupRequestToJSONTyped(json, false);
}

export function SignupRequestToJSONTyped(value?: SignupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_name': value['userName'],
        'email': value['email'],
        'password': value['password'],
    };
}

