/* tslint:disable */
/* eslint-disable */
/**
 * nongo for Bushigen
 * Management system for Bushigen family
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response data for software engineer
 * @export
 * @interface SoftwareEngineerResponse
 */
export interface SoftwareEngineerResponse {
    /**
     * Unique identifier of the software engineer
     * @type {number}
     * @memberof SoftwareEngineerResponse
     */
    id?: number;
    /**
     * Name of the software engineer
     * @type {string}
     * @memberof SoftwareEngineerResponse
     */
    name?: string;
    /**
     * Technology stack and skills
     * @type {string}
     * @memberof SoftwareEngineerResponse
     */
    techStack?: string;
}

/**
 * Check if a given object implements the SoftwareEngineerResponse interface.
 */
export function instanceOfSoftwareEngineerResponse(value: object): value is SoftwareEngineerResponse {
    return true;
}

export function SoftwareEngineerResponseFromJSON(json: any): SoftwareEngineerResponse {
    return SoftwareEngineerResponseFromJSONTyped(json, false);
}

export function SoftwareEngineerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoftwareEngineerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'techStack': json['techStack'] == null ? undefined : json['techStack'],
    };
}

export function SoftwareEngineerResponseToJSON(json: any): SoftwareEngineerResponse {
    return SoftwareEngineerResponseToJSONTyped(json, false);
}

export function SoftwareEngineerResponseToJSONTyped(value?: SoftwareEngineerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'techStack': value['techStack'],
    };
}

