/* tslint:disable */
/* eslint-disable */
/**
 * nongo for Bushigen
 * Management system for Bushigen family
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Software Engineer entity
 * @export
 * @interface SoftwareEngineer
 */
export interface SoftwareEngineer {
    /**
     * Unique identifier of the software engineer
     * @type {number}
     * @memberof SoftwareEngineer
     */
    id?: number;
    /**
     * Name of the software engineer
     * @type {string}
     * @memberof SoftwareEngineer
     */
    name?: string;
    /**
     * Technology stack and skills
     * @type {string}
     * @memberof SoftwareEngineer
     */
    techStack?: string;
}

/**
 * Check if a given object implements the SoftwareEngineer interface.
 */
export function instanceOfSoftwareEngineer(value: object): value is SoftwareEngineer {
    return true;
}

export function SoftwareEngineerFromJSON(json: any): SoftwareEngineer {
    return SoftwareEngineerFromJSONTyped(json, false);
}

export function SoftwareEngineerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoftwareEngineer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'techStack': json['techStack'] == null ? undefined : json['techStack'],
    };
}

export function SoftwareEngineerToJSON(json: any): SoftwareEngineer {
    return SoftwareEngineerToJSONTyped(json, false);
}

export function SoftwareEngineerToJSONTyped(value?: SoftwareEngineer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'techStack': value['techStack'],
    };
}

