/* tslint:disable */
/* eslint-disable */
/**
 * nongo for Bushigen
 * Management system for Bushigen family
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Software engineer data to create (ID will be auto-generated)
 * @export
 * @interface SoftwareEngineerCreateRequest
 */
export interface SoftwareEngineerCreateRequest {
    /**
     * Name of the software engineer
     * @type {string}
     * @memberof SoftwareEngineerCreateRequest
     */
    name: string;
    /**
     * Technology stack and skills
     * @type {string}
     * @memberof SoftwareEngineerCreateRequest
     */
    techStack: string;
}

/**
 * Check if a given object implements the SoftwareEngineerCreateRequest interface.
 */
export function instanceOfSoftwareEngineerCreateRequest(value: object): value is SoftwareEngineerCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('techStack' in value) || value['techStack'] === undefined) return false;
    return true;
}

export function SoftwareEngineerCreateRequestFromJSON(json: any): SoftwareEngineerCreateRequest {
    return SoftwareEngineerCreateRequestFromJSONTyped(json, false);
}

export function SoftwareEngineerCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoftwareEngineerCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'techStack': json['techStack'],
    };
}

export function SoftwareEngineerCreateRequestToJSON(json: any): SoftwareEngineerCreateRequest {
    return SoftwareEngineerCreateRequestToJSONTyped(json, false);
}

export function SoftwareEngineerCreateRequestToJSONTyped(value?: SoftwareEngineerCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'techStack': value['techStack'],
    };
}

