/* tslint:disable */
/* eslint-disable */
/**
 * nongo for Bushigen
 * Management system for Bushigen family
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SoftwareEngineerUpdateRequest
 */
export interface SoftwareEngineerUpdateRequest {
    /**
     * ID of the software engineer
     * @type {number}
     * @memberof SoftwareEngineerUpdateRequest
     */
    id: number;
    /**
     * Name of the software engineer
     * @type {string}
     * @memberof SoftwareEngineerUpdateRequest
     */
    name: string;
    /**
     * Technology stack and skills
     * @type {string}
     * @memberof SoftwareEngineerUpdateRequest
     */
    techStack: string;
}

/**
 * Check if a given object implements the SoftwareEngineerUpdateRequest interface.
 */
export function instanceOfSoftwareEngineerUpdateRequest(value: object): value is SoftwareEngineerUpdateRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('techStack' in value) || value['techStack'] === undefined) return false;
    return true;
}

export function SoftwareEngineerUpdateRequestFromJSON(json: any): SoftwareEngineerUpdateRequest {
    return SoftwareEngineerUpdateRequestFromJSONTyped(json, false);
}

export function SoftwareEngineerUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoftwareEngineerUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'techStack': json['techStack'],
    };
}

export function SoftwareEngineerUpdateRequestToJSON(json: any): SoftwareEngineerUpdateRequest {
    return SoftwareEngineerUpdateRequestToJSONTyped(json, false);
}

export function SoftwareEngineerUpdateRequestToJSONTyped(value?: SoftwareEngineerUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'techStack': value['techStack'],
    };
}

