/* tslint:disable */
/* eslint-disable */
/**
 * nongo for Bushigen
 * Management system for Bushigen family
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SoftwareEngineerCreateRequest,
  SoftwareEngineerResponse,
  SoftwareEngineerUpdateRequest,
} from '../models/index';
import {
    SoftwareEngineerCreateRequestFromJSON,
    SoftwareEngineerCreateRequestToJSON,
    SoftwareEngineerResponseFromJSON,
    SoftwareEngineerResponseToJSON,
    SoftwareEngineerUpdateRequestFromJSON,
    SoftwareEngineerUpdateRequestToJSON,
} from '../models/index';

export interface AddNewSoftwareEngineerRequest {
    softwareEngineerCreateRequest: SoftwareEngineerCreateRequest;
}

export interface DeleteSoftwareEngineerByIdRequest {
    body: number;
}

export interface EditSoftwareEngineerRequest {
    softwareEngineerUpdateRequest: SoftwareEngineerUpdateRequest;
}

export interface GetEngineersByIdRequest {
    id: number;
}

/**
 * 
 */
export class SoftwareEngineerApi extends runtime.BaseAPI {

    /**
     * Add a new software engineer to the system
     * Create new software engineer
     */
    async addNewSoftwareEngineerRaw(requestParameters: AddNewSoftwareEngineerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['softwareEngineerCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'softwareEngineerCreateRequest',
                'Required parameter "softwareEngineerCreateRequest" was null or undefined when calling addNewSoftwareEngineer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/software-engineers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SoftwareEngineerCreateRequestToJSON(requestParameters['softwareEngineerCreateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a new software engineer to the system
     * Create new software engineer
     */
    async addNewSoftwareEngineer(requestParameters: AddNewSoftwareEngineerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addNewSoftwareEngineerRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a software engineer by ID
     * Delete software engineer
     */
    async deleteSoftwareEngineerByIdRaw(requestParameters: DeleteSoftwareEngineerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling deleteSoftwareEngineerById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/software-engineers/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a software engineer by ID
     * Delete software engineer
     */
    async deleteSoftwareEngineerById(requestParameters: DeleteSoftwareEngineerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.deleteSoftwareEngineerByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing software engineer
     * Update software engineer
     */
    async editSoftwareEngineerRaw(requestParameters: EditSoftwareEngineerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['softwareEngineerUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'softwareEngineerUpdateRequest',
                'Required parameter "softwareEngineerUpdateRequest" was null or undefined when calling editSoftwareEngineer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/software-engineers/edit`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SoftwareEngineerUpdateRequestToJSON(requestParameters['softwareEngineerUpdateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update an existing software engineer
     * Update software engineer
     */
    async editSoftwareEngineer(requestParameters: EditSoftwareEngineerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.editSoftwareEngineerRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve a list of all software engineers
     * Get all software engineers
     */
    async getEngineersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SoftwareEngineerResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/software-engineers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SoftwareEngineerResponseFromJSON));
    }

    /**
     * Retrieve a list of all software engineers
     * Get all software engineers
     */
    async getEngineers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SoftwareEngineerResponse>> {
        const response = await this.getEngineersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific software engineer by their ID
     * Get software engineer by ID
     */
    async getEngineersByIdRaw(requestParameters: GetEngineersByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SoftwareEngineerResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEngineersById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/software-engineers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SoftwareEngineerResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific software engineer by their ID
     * Get software engineer by ID
     */
    async getEngineersById(requestParameters: GetEngineersByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SoftwareEngineerResponse> {
        const response = await this.getEngineersByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
