package bushigen.nongo.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * DTO for creating new SoftwareEngineer records.
 * Note: No ID field as it's auto-generated by the database.
 */

public record SoftwareEngineerCreateRequest(
    @Schema(description = "Name of the software engineer", example = "田中太郎", required = true)
    String name,
    @Schema(description = "Technology stack and skills", example = "Java, Spring Boot, MySQL")
    String techStack
) {}